import type { AnalysisReport, HealthResponse, HistoryRow, NegotiationRecommendation, OrgUsage, ApiKey } from "../types"

/*
 * Offline fallbacks. When the FastAPI backend is unreachable the UI degrades to
 * this representative data instead of showing dead screens.
 */

export const demoHealth: HealthResponse = {
  status: "ok",
  model: "gemini-2.0-flash",
  langsmith_enabled: true,
  langsmith_project: "monarch-prod",
  rag_total_documents: 128,
}

export const demoReport: AnalysisReport = {
  report_id: "rep_demo_001",
  buyer_name: "Buyer Enterprise Pvt Ltd",
  file_name: "supply-agreement.pdf",
  compliance_score: 38,
  risk_level: "critical",
  analyzed_at: new Date().toISOString(),
  overall_summary:
    "The agreement sets a 90 day payment cycle, waives penal interest and allows unilateral termination. Each of these conflicts with the MSMED Act 2006 and together they expose the buyer to statutory interest and loss of the expense deduction under Section 43B(h).",
  disclaimer:
    "This analysis is generated by an AI system for informational purposes. It is not legal advice. Verify with qualified counsel before initiating statutory proceedings.",
  contact_attempts: 1,
  first_contact_date: new Date(Date.now() - 86400000 * 12).toISOString(),
  violations: [
    {
      clause_text:
        "Payment against all accepted invoices shall be released within ninety (90) days from the date of receipt of a valid invoice at the Buyer's registered office.",
      violation_type: "payment_cycle",
      cited_law: "Section 15, MSMED Act 2006",
      cited_chunk_id: "msmed_s15_002",
      severity: "critical",
      samadhaan_ready: true,
      confidence: 0.94,
      needs_human_review: false,
      draft_counter_clause:
        "Payment against all accepted invoices shall be released within forty-five (45) days from the date of acceptance or deemed acceptance of goods or services, in accordance with Section 15 of the MSMED Act 2006.",
      evidence: {
        source_text: "No buyer shall make payment later than forty-five days from the day of acceptance or the day of deemed acceptance.",
        clause_reference: "Clause 7.2",
        page_number: 4,
        statute_ref: "MSMED Act s.15",
        matched_keywords: ["ninety days", "payment", "invoice"],
      },
      financial_impact: {
        estimated_delay_days: 45,
        statutory_interest_rate_percent: 19.5,
        estimated_interest_exposure: 92500,
        tax_disallowance_risk: true,
        estimated_tax_exposure: 375000,
        total_financial_exposure: 467500,
      },
    },
    {
      clause_text: "No interest shall be payable by the Buyer on account of any delay in release of payment, howsoever caused.",
      violation_type: "interest_penalty",
      cited_law: "Section 16, MSMED Act 2006",
      cited_chunk_id: "msmed_s16_001",
      severity: "high",
      samadhaan_ready: true,
      confidence: 0.91,
      draft_counter_clause:
        "Any delay beyond the statutory period shall attract compound interest with monthly rests at three times the bank rate notified by the Reserve Bank of India, as mandated by Section 16 of the MSMED Act 2006. This entitlement cannot be waived by agreement.",
      evidence: {
        source_text: "The buyer shall be liable to pay compound interest with monthly rests at three times the bank rate notified by the Reserve Bank.",
        clause_reference: "Clause 7.5",
        page_number: 4,
        statute_ref: "MSMED Act s.16",
        matched_keywords: ["no interest", "delay"],
      },
      financial_impact: {
        estimated_delay_days: 45,
        statutory_interest_rate_percent: 19.5,
        estimated_interest_exposure: 92500,
        tax_disallowance_risk: false,
        estimated_tax_exposure: 0,
        total_financial_exposure: 92500,
      },
    },
    {
      clause_text: "The Buyer may terminate this Agreement at its sole discretion at any time without assigning any reason and without liability.",
      violation_type: "unilateral_cancellation",
      cited_law: "Unfair contract term, read with MSMED Act 2006",
      severity: "medium",
      samadhaan_ready: false,
      confidence: 0.62,
      needs_human_review: true,
      draft_counter_clause:
        "Either party may terminate this Agreement on thirty (30) days written notice. Goods delivered or services rendered prior to the effective date of termination shall be paid for within the statutory period.",
      evidence: {
        source_text: "Termination rights that are exercisable by one party alone and without compensation are commercially unconscionable.",
        clause_reference: "Clause 12.1",
        page_number: 9,
        matched_keywords: ["sole discretion", "without liability"],
      },
    },
  ],
  financial_summary: {
    estimated_delay_days: 45,
    statutory_interest_rate_percent: 19.5,
    estimated_interest_exposure: 92500,
    tax_disallowance_risk: true,
    estimated_tax_exposure: 375000,
    total_financial_exposure: 467500,
    months_overdue: 4,
    monthly_compound_rate: 1.625,
    rbi_bank_rate: 6.5,
    principal_amount: 1500000,
    total_recoverable: 1592500,
    calculation_method: "compound_monthly_rests",
  },
  review_decision: {
    needs_human_review: true,
    review_reasons: [
      "One violation was detected with confidence below the 0.7 auto-approval threshold.",
      "Total exposure exceeds the review threshold of four lakh rupees.",
    ],
    confidence_score: 0.82,
    auto_approved: false,
    flags: ["low_confidence_violation", "high_value_claim"],
    recommended_action: "review",
  },
  risk_score_disclaimer:
    "Scores are heuristic and weighted by statutory severity. They support negotiation and triage, not adjudication.",
  risk_score_breakdown: [
    { deduction_name: "payment_cycle_breach", points_deducted: 35, rationale: "Payment window of 90 days exceeds the 45 day statutory ceiling.", triggered: true },
    { deduction_name: "interest_waiver", points_deducted: 20, rationale: "Clause purports to waive interest that cannot be waived under s.16.", triggered: true },
    { deduction_name: "unilateral_termination", points_deducted: 7, rationale: "Termination at sole discretion with no compensation.", triggered: true },
    { deduction_name: "dispute_forum_exclusion", points_deducted: 15, rationale: "Facilitation Council jurisdiction was not excluded.", triggered: false },
  ],
  recommended_actions: [
    { action_id: "send_demand", label: "Send a payment demand citing s.15 and s.16", effort_level: "low", is_recommended: true, reason: "Only one contact attempt has been logged; a written statutory demand is the cheapest next step.", escalation_order: 1 },
    { action_id: "formal_notice", label: "Issue a formal legal notice", effort_level: "medium", is_recommended: false, reason: "Appropriate if the demand goes unanswered for 15 days.", escalation_order: 2 },
    { action_id: "file_samadhaan", label: "File a Samadhaan reference under s.18", effort_level: "high", is_recommended: false, reason: "Available once the statutory period has clearly lapsed and the demand has failed.", escalation_order: 3 },
  ],
  draft_samadhaan_complaint: `BEFORE THE MICRO AND SMALL ENTERPRISES FACILITATION COUNCIL
Reference under Section 18 of the MSMED Act, 2006

1. The Applicant is a registered Small Enterprise under the MSMED Act, 2006.
2. The Respondent, Buyer Enterprise Pvt Ltd, placed orders which were duly executed and accepted.
3. Invoices aggregating INR 15,00,000 fell due for payment within forty-five days of acceptance under Section 15.
4. Payment remains outstanding beyond the statutory period. Clause 7.2 of the agreement stipulating a ninety day cycle is void to the extent it conflicts with Section 15.
5. Clause 7.5 purporting to waive interest is unenforceable in view of Section 16, which mandates compound interest with monthly rests at three times the Reserve Bank of India bank rate.
6. Interest computed to date amounts to INR 92,500, with the aggregate claim standing at INR 15,92,500.

PRAYER
The Applicant respectfully prays that this Council be pleased to:
  (a) direct the Respondent to pay the principal amount of INR 15,00,000;
  (b) award statutory compound interest under Section 16 until realisation;
  (c) grant such further relief as the Council deems fit.

Place: ____________          Signature: ____________
Date:  ____________          Authorised Signatory`,
}

export const demoHistory: HistoryRow[] = [
  {
    id: "rep_demo_001",
    buyer_name: "Buyer Enterprise Pvt Ltd",
    file_name: "supply-agreement.pdf",
    compliance_score: 38,
    violations_count: 3,
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
    report_data: demoReport,
  },
  {
    id: "rep_demo_002",
    buyer_name: "Northline Motors Ltd",
    file_name: "msa-northline.docx",
    compliance_score: 64,
    violations_count: 2,
    created_at: new Date(Date.now() - 86400000 * 9).toISOString(),
    report_data: { ...demoReport, report_id: "rep_demo_002", buyer_name: "Northline Motors Ltd", compliance_score: 64, risk_level: "medium" },
  },
  {
    id: "rep_demo_003",
    buyer_name: "Sunreach Textiles",
    file_name: "purchase-order-terms.pdf",
    compliance_score: 82,
    violations_count: 1,
    created_at: new Date(Date.now() - 86400000 * 21).toISOString(),
    report_data: { ...demoReport, report_id: "rep_demo_003", buyer_name: "Sunreach Textiles", compliance_score: 82, risk_level: "low" },
  },
]

export const demoNegotiation: NegotiationRecommendation[] = [
  {
    original_clause: "Payment within ninety (90) days with no interest on delay.",
    violation_type: "payment_cycle",
    cited_law: "Section 15 and 16, MSMED Act 2006",
    compliant_replacement:
      "Payment shall be made within forty-five (45) days of acceptance. Any delay shall attract compound interest with monthly rests at three times the RBI bank rate under Section 16 of the MSMED Act 2006.",
    risk_explanation:
      "A ninety day cycle is void against a registered micro or small enterprise, and the buyer additionally loses the expense deduction under Section 43B(h) until payment is actually made.",
    confidence: 0.93,
  },
]

export const demoUsage: OrgUsage = {
  org_id: "demo_org",
  plan: "pro",
  usage: { analyses: 12, documents: 23, chat_messages: 184 },
  limits: { analyses: 50, documents: 100, chat_messages: 1000, api_access: true, price_inr: 999, name: "Pro Plan" },
}

export const demoDocuments = {
  document_count: 14,
  documents: [
    { source: "msmed-act-2006.pdf", chunk_index: 0 },
    { source: "msmed-act-2006.pdf", chunk_index: 1 },
    { source: "msmed-act-2006.pdf", chunk_index: 2 },
    { source: "supply-agreement.pdf", chunk_index: 0 },
    { source: "supply-agreement.pdf", chunk_index: 1 },
    { source: "rbi-bank-rate-circular.pdf", chunk_index: 0 },
  ],
}

export const demoMemories: string[] = [
  "We are a registered Small enterprise with Udyam registration UDYAM-TN-01-0001234.",
  "Standard payment terms offered to buyers are 30 days from acceptance.",
  "Escalate any claim above ten lakh rupees to external counsel before filing.",
]

export const demoKeys: ApiKey[] = [
  { key_id: "key_001", name: "ERP integration", key_prefix: "wmb_live_8fa2", created_at: new Date(Date.now() - 86400000 * 40).toISOString(), last_used_at: new Date(Date.now() - 3600000 * 5).toISOString(), revoked: false },
  { key_id: "key_002", name: "Finance automation", key_prefix: "wmb_live_1c77", created_at: new Date(Date.now() - 86400000 * 120).toISOString(), last_used_at: null, revoked: true },
]
